# Pure Python vs. Numpy - Lab

## Introduction 

Numpy, Scipy, and Pandas provide a significant increase in computational efficiency with complex mathematical operations as compared to Python's built-in arithmetic functions. In this lab, you will calculate and compare the processing speed required for calculating a dot product using both basic arithmetic operations in Python and Numpy's `.dot()` method. 

## Objectives
You will be able to:

- Compare the performance of high-dimensional matrix operations in Numpy vs. pure Python

## Problem 

Write a routine to calculate the dot product between two $200 \times 200$ dimensional matrices using:

a) Pure Python (no libraries)

b) Numpy's `.dot()` method 


### Create two $200 \times 200$ matrices in Python and fill them with random values using `np.random.rand()` 

In [6]:
a00b00+a01b10

3

In [41]:
# Compare 200x200 matrix-matrix multiplication speed
import numpy as np

def multiply(A,B):
    A_rows=A.shape[0]
    A_columns=A.shape[1]
    B_columns=B.shape[1]
    product=np.zeros(shape=(A_rows,B_columns))
    
    for k in range(B_columns):    
        for j in range(A_rows):
            answer=0
            for i in range(A_columns):
                answer+=A[j][i]*B[i][k]
            product[j][k]=answer

    return product

# Set up the variables
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A)
print(B)

print(multiply(A,B))
print(np.dot(A,B))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19. 22.]
 [43. 50.]]
[[19 22]
 [43 50]]


## Pure Python

* Initialize a zeros-filled `numpy` matrix
* In Python, calculate the dot product using the formula 


$$ \large C_{i,j}= \sum_k A_{i,k}B_{k,j}$$


* Use Python's `timeit` library to calculate the processing time
* [Visit this link](https://www.pythoncentral.io/time-a-python-function/) for an in-depth explanation on how to time a function or routine in Python

**Hint**: Use a nested `for` loop for accessing, calculating, and storing each scalar value in the resulting matrix. 

In [46]:
import timeit

A = np.zeros(shape=(200,200))
B = np.zeros(shape=(200,200))
for i in range(200*200):
    A[i//200][i%200]=np.random.randint(0,11)
    B[i//200][i%200]=np.random.randint(0,11)

# Start the timer
start = timeit.default_timer()

# Matrix multiplication in pure Python
multiply(A,B)

time_spent = timeit.default_timer() - start

print('Pure Python time:', time_spent, 'sec.')

Pure Python time: 15.128939000000173 sec.


## Numpy 
Set the timer and calculate the time taken by the `.dot()` method for multiplying $A$ and $B$ 


In [47]:
# Start the timer
start = timeit.default_timer()

# Matrix multiplication in numpy
np.dot(A,B)

time_spent = timeit.default_timer() - start
print('Numpy time:', time_spent, 'sec.')

Numpy time: 0.7943900999998732 sec.


### Your comments

## Summary

In this lab, you performed a quick comparison between calculating a dot product in Numpy vs pure Python. You saw that Numpy is computationally much more efficient than pure Python code because of the sophisticated implementation of Numpy source code. You're encouraged to always perform time tests to fully appreciate the use of an additional library in Python. 